/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Controlador.Controlador;
import Logica.Archivo;
import Logica.Ordenamiento;
import java.awt.Color;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Carlos Narvaez
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private final FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo ARFF", "arff");
    DefaultTableModel modelo, modeloProcesado, modeloOrdenamiento;
    ArrayList<String[]> listaParametros;
    ArrayList<Integer> listaEdad = new ArrayList<>();
    ArrayList<Double> listaNa = new ArrayList<>();
    ArrayList<Double> listaK = new ArrayList<>();
    String ruta;
    String[] calculosOrdenamiento;
    
    String[][] datos = new String[200][7];
    String[][] datosProcesados;
    
    Controlador controlador = new Controlador();
    
    public Principal() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
        menuEntrenamiento.setBackground(Color.white);
        this.setLocationRelativeTo(null);
        crearTablaInicial();
    }
    
    public final void crearTablaInicial() {
        modelo = new DefaultTableModel();
        modeloProcesado = new DefaultTableModel();
        modeloOrdenamiento = new DefaultTableModel();
        
        modelo.addColumn("Edad");           modeloProcesado.addColumn("Edad");
        modelo.addColumn("Sexo");           modeloProcesado.addColumn("Sexo");
        modelo.addColumn("BP");             modeloProcesado.addColumn("BP");
        modelo.addColumn("Colesterol");     modeloProcesado.addColumn("Colesterol");
        modelo.addColumn("Na");             modeloProcesado.addColumn("Na");
        modelo.addColumn("K");              modeloProcesado.addColumn("K");
        modelo.addColumn("Droga");          modeloProcesado.addColumn("Droga");
        
        modeloOrdenamiento.addColumn("Edad");
        modeloOrdenamiento.addColumn("Edad delta");
        modeloOrdenamiento.addColumn("Distic");
        modeloOrdenamiento.addColumn("Na");
        modeloOrdenamiento.addColumn("Na delta");
        modeloOrdenamiento.addColumn("Distic");
        modeloOrdenamiento.addColumn("K");
        modeloOrdenamiento.addColumn("K delta");
        modeloOrdenamiento.addColumn("Distic");
        
        this.tablaDatosOriginales.setModel(modelo);
        this.tablaDatosProcesados.setModel(modeloProcesado);
        this.tablaOrdenamiento.setModel(modeloOrdenamiento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatosOriginales = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDatosProcesados = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaOrdenamiento = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menuEntrenamiento = new javax.swing.JPanel();
        btnRealizarEntrenamiento = new javax.swing.JButton();
        txtDeltaEdad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDisticEdad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDeltaNa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDisticNa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPrecisionEdad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPrecisionNa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDeltaK = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDisticK = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPrecisionK = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAbrir = new javax.swing.JMenu();
        menuSeleccionarArchivo = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        menuTablas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1175, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDatosOriginales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaDatosOriginales);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, 550, 360));

        jLabel1.setText("Datos originales:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        tablaDatosProcesados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaDatosProcesados);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 550, 360));

        tablaOrdenamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaOrdenamiento);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 550, 180));

        jLabel2.setText("Datos procesados:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 130, -1));

        jLabel3.setText("Ordenamiento:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 90, -1));

        menuEntrenamiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Menú"));

        btnRealizarEntrenamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entrenamiento_boton_negro.png"))); // NOI18N
        btnRealizarEntrenamiento.setBorder(null);
        btnRealizarEntrenamiento.setBorderPainted(false);
        btnRealizarEntrenamiento.setContentAreaFilled(false);
        btnRealizarEntrenamiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRealizarEntrenamiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRealizarEntrenamiento.setIconTextGap(-3);
        btnRealizarEntrenamiento.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entrenamiento_boton_azul.png"))); // NOI18N
        btnRealizarEntrenamiento.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRealizarEntrenamiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRealizarEntrenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarEntrenamientoActionPerformed(evt);
            }
        });

        jLabel4.setText("Delta edad:");

        jLabel5.setText("Distict edad:");

        jLabel6.setText("Delta Na:");

        jLabel7.setText("Distict Na:");

        jLabel8.setText("Precisión:");

        jLabel9.setText("Precisión:");

        jLabel10.setText("Delta K:");

        jLabel11.setText("Distict K:");

        jLabel12.setText("Precisión:");

        javax.swing.GroupLayout menuEntrenamientoLayout = new javax.swing.GroupLayout(menuEntrenamiento);
        menuEntrenamiento.setLayout(menuEntrenamientoLayout);
        menuEntrenamientoLayout.setHorizontalGroup(
            menuEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuEntrenamientoLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(menuEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRealizarEntrenamiento)
                    .addGroup(menuEntrenamientoLayout.createSequentialGroup()
                        .addGroup(menuEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDeltaEdad)
                            .addComponent(txtDeltaNa)
                            .addComponent(txtDeltaK, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(menuEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(menuEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDisticEdad)
                            .addComponent(txtDisticNa)
                            .addComponent(txtDisticK, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(menuEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(menuEntrenamientoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecisionEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menuEntrenamientoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecisionNa))
                            .addGroup(menuEntrenamientoLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecisionK)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        menuEntrenamientoLayout.setVerticalGroup(
            menuEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuEntrenamientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(txtDisticEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeltaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtPrecisionEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtDeltaNa)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(menuEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDisticNa)
                            .addComponent(jLabel9)
                            .addComponent(txtPrecisionNa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(menuEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(menuEntrenamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDeltaK)
                        .addComponent(jLabel11)
                        .addComponent(txtDisticK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(txtPrecisionK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnRealizarEntrenamiento)
                .addContainerGap())
        );

        getContentPane().add(menuEntrenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 570, 220));

        jMenu1.setText("Archivo");

        menuAbrir.setText("Abrir");
        menuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirActionPerformed(evt);
            }
        });

        menuSeleccionarArchivo.setText("Seleccionar archivo");
        menuSeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSeleccionarArchivoActionPerformed(evt);
            }
        });
        menuAbrir.add(menuSeleccionarArchivo);

        jMenu1.add(menuAbrir);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        menuTablas.setText("Tablas de probabilidad");
        menuTablas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTablasMouseClicked(evt);
            }
        });
        menuTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTablasActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuTablas);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuAbrirActionPerformed

    private void menuSeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSeleccionarArchivoActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser filechoose = new JFileChooser();
            modelo.setRowCount(0);
            int opcion = filechoose.showOpenDialog(this);
            filechoose.setFileFilter(filter);

            if(opcion == JFileChooser.APPROVE_OPTION) {
                ruta = filechoose.getSelectedFile().getPath();
            }

            listaParametros = controlador.leerDatosArchivo(ruta);
            
            listaParametros.stream().forEach((listaParametro) -> {
                modelo.addRow(listaParametro);
            });
            
            for (int i = 0; i < listaParametros.size(); i++) {
                for (int j = 0; j < listaParametros.get(i).length; j++) {
                    datos[i][j] = listaParametros.get(i)[j];
                }
            }
            
            for (int i = 0; i < 200; i++) {
                listaEdad.add(Integer.parseInt(datos[i][0]));
                listaNa.add(Double.parseDouble(datos[i][4]));
                listaK.add(Double.parseDouble(datos[i][5]));
                
            }        
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Se ha cancelado la carga del archivo", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        

    }//GEN-LAST:event_menuSeleccionarArchivoActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void btnRealizarEntrenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarEntrenamientoActionPerformed
        // TODO add your handling code here:
        modeloOrdenamiento.setRowCount(0);
        Collections.sort(listaEdad);
        Collections.sort(listaNa);
        Collections.sort(listaK);
        
        String[] linea = new String[9];
        linea[0] = Integer.toString(listaEdad.get(0));
        linea[3] = Double.toString(listaNa.get(0));
        linea[6] = Double.toString(listaK.get(0));
        modeloOrdenamiento.addRow(linea);
        
        
        for (int i = 1; i < listaParametros.size(); i++) {
            
            modeloOrdenamiento.addRow(controlador.datosOrdenados(listaEdad, listaNa, listaK, i));
        }
        
        calculosOrdenamiento = controlador.calculosOrdenamiento(listaEdad, listaNa, listaK);
        
        txtDeltaEdad.setText(calculosOrdenamiento[0]);
        txtDisticEdad.setText(calculosOrdenamiento[1]);
        txtDeltaNa.setText(calculosOrdenamiento[2]);
        txtDisticNa.setText(calculosOrdenamiento[3]);
        txtDeltaK.setText(calculosOrdenamiento[4]);
        txtDisticK.setText(calculosOrdenamiento[5]);
        txtPrecisionEdad.setText(calculosOrdenamiento[6]);
        txtPrecisionNa.setText(calculosOrdenamiento[7]);
        txtPrecisionK.setText(calculosOrdenamiento[8]);
        
        datosProcesados = datos;
        
        ArrayList<Integer> l1 = new ArrayList<>();
        ArrayList<Double> l2 = new ArrayList<>();
        ArrayList<Double> l3 = new ArrayList<>();
        
        for (int i = 0; i < 200; i++) {
            l1.add(Integer.parseInt(datos[i][0]));
            l2.add(Double.parseDouble(datos[i][4]));
            l3.add(Double.parseDouble(datos[i][5]));
        }
        
        
        ArrayList<String> ledad = controlador.procesarDatosEntero(l1, Double.parseDouble(calculosOrdenamiento[6]));
        ArrayList<String> lna = controlador.procesarDatosDecimales(l2, Double.parseDouble(calculosOrdenamiento[7]));
        ArrayList<String> lk = controlador.procesarDatosDecimales(l3, Double.parseDouble(calculosOrdenamiento[8]));
        
        for (int i = 0; i < ledad.size(); i++) {
            datosProcesados[i][0] = ledad.get(i);
            datosProcesados[i][4] = lna.get(i);
            datosProcesados[i][5] = lk.get(i);
        }
        
        
        
        String[] vector = new String[7];
        for (int i = 0; i < 200; i++) {
            for (int j = 0; j < 7; j++) {
                vector[j] = datosProcesados[i][j];
            }
            modeloProcesado.addRow(vector);
        }
        
        controlador.obtenerTablasProbabilidad(datosProcesados, calculosOrdenamiento);

    }//GEN-LAST:event_btnRealizarEntrenamientoActionPerformed

    private void menuTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablasActionPerformed
        // TODO add your handling code here:
        System.out.println("Suma distict K: ");
    }//GEN-LAST:event_menuTablasActionPerformed

    private void menuTablasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTablasMouseClicked
        // TODO add your handling code here:
        Archivo ar = new Archivo();
        ar.escribirArchivo(datosProcesados);
    }//GEN-LAST:event_menuTablasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarEntrenamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenu menuAbrir;
    private javax.swing.JPanel menuEntrenamiento;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuSeleccionarArchivo;
    private javax.swing.JMenu menuTablas;
    private javax.swing.JTable tablaDatosOriginales;
    private javax.swing.JTable tablaDatosProcesados;
    private javax.swing.JTable tablaOrdenamiento;
    private javax.swing.JTextField txtDeltaEdad;
    private javax.swing.JTextField txtDeltaK;
    private javax.swing.JTextField txtDeltaNa;
    private javax.swing.JTextField txtDisticEdad;
    private javax.swing.JTextField txtDisticK;
    private javax.swing.JTextField txtDisticNa;
    private javax.swing.JTextField txtPrecisionEdad;
    private javax.swing.JTextField txtPrecisionK;
    private javax.swing.JTextField txtPrecisionNa;
    // End of variables declaration//GEN-END:variables
}
